include $(THEOS)/makefiles/common.mk

TWEAK_NAME = KeySwipe

KeySwipe_FILES = /mnt/d/codes/keyswipe/Tweak.xm
KeySwipe_FRAMEWORKS = CydiaSubstrate UIKit CoreGraphics

export ARCHS = arm64

include $(THEOS_MAKE_PATH)/tweak.mk
	
all::
